//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.ListaEventoes = new HashSet<ListaEvento>();
            this.ListaEventoes1 = new HashSet<ListaEvento>();
            this.ListaFavoritos = new HashSet<ListaFavorito>();
            this.ListaFavoritos1 = new HashSet<ListaFavorito>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Email { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual ICollection<ListaEvento> ListaEventoes { get; set; }
        public virtual ICollection<ListaEvento> ListaEventoes1 { get; set; }
        public virtual ICollection<ListaFavorito> ListaFavoritos { get; set; }
        public virtual ICollection<ListaFavorito> ListaFavoritos1 { get; set; }
    }
}
