//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Direccion
    {
        public Direccion()
        {
            this.Eventoes = new HashSet<Evento>();
            this.Locals = new HashSet<Local>();
            this.Locals1 = new HashSet<Local>();
        }
    
        public int Id { get; set; }
        public string Calle { get; set; }
        public string Población { get; set; }
        public string CodigoPostal { get; set; }
    
        public virtual ICollection<Evento> Eventoes { get; set; }
        public virtual ICollection<Local> Locals { get; set; }
        public virtual ICollection<Local> Locals1 { get; set; }
    }
}
