//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccion
    {
        public direccion()
        {
            this.eventoes = new HashSet<evento>();
            this.locals = new HashSet<local>();
        }
    
        public int id { get; set; }
        public string calle { get; set; }
        public string municipio { get; set; }
        public int codigoPostal { get; set; }
    
        public virtual ICollection<evento> eventoes { get; set; }
        public virtual ICollection<local> locals { get; set; }
    }
}
