//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public evento()
        {
            this.flyers = new HashSet<flyer>();
            this.listaeventoes = new HashSet<listaevento>();
        }
    
        public int id { get; set; }
        public int idLocal { get; set; }
        public int idDireccion { get; set; }
        public int idTipoEvento { get; set; }
        public int idEstilo { get; set; }
        public System.DateTime fecha { get; set; }
        public int aforo { get; set; }
        public string descripcion { get; set; }
    
        public virtual direccion direccion { get; set; }
        public virtual estilo estilo { get; set; }
        public virtual tipoevento tipoevento { get; set; }
        public virtual local local { get; set; }
        public virtual ICollection<flyer> flyers { get; set; }
        public virtual ICollection<listaevento> listaeventoes { get; set; }
    }
}
