//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public Evento()
        {
            this.Flyer = new HashSet<Flyer>();
            this.Flyer1 = new HashSet<Flyer>();
            this.ListaEvento = new HashSet<ListaEvento>();
            this.ListaEvento1 = new HashSet<ListaEvento>();
        }
    
        public int Id { get; set; }
        public int IdDireccion { get; set; }
        public int IdTipoEvento { get; set; }
        public int IdEstilo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Aforo { get; set; }
        public string Descripcion { get; set; }
        public int IdLocal { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Estilo Estilo { get; set; }
        public virtual Local Local { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual ICollection<Flyer> Flyer { get; set; }
        public virtual ICollection<Flyer> Flyer1 { get; set; }
        public virtual ICollection<ListaEvento> ListaEvento { get; set; }
        public virtual ICollection<ListaEvento> ListaEvento1 { get; set; }
    }
}
