//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    //pos vale lmkpm
    public partial class flyer
    {
        public int id { get; set; }
        public string url { get; set; }
        public int idEvento { get; set; }
    
        public virtual evento evento { get; set; }
    }
}
