//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaEvento
    {
        public int IdEvento { get; set; }
        public int IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Evento Evento { get; set; }
        public virtual Evento Evento1 { get; set; }
    }
}
