//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class listafavorito
    {
        public int id { get; set; }
        public int idCliente { get; set; }
        public int idLocal { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual local local { get; set; }
    }
}
