//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public Local()
        {
            this.Evento = new HashSet<Evento>();
            this.ListaFavoritos = new HashSet<ListaFavoritos>();
            this.ListaFavoritos1 = new HashSet<ListaFavoritos>();
        }
    
        public int IdTipoLocal { get; set; }
        public int IdDireccion { get; set; }
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public int IdUsuario { get; set; }
    
        public virtual Direccion Direccion { get; set; }
        public virtual Direccion Direccion1 { get; set; }
        public virtual ICollection<Evento> Evento { get; set; }
        public virtual ICollection<ListaFavoritos> ListaFavoritos { get; set; }
        public virtual ICollection<ListaFavoritos> ListaFavoritos1 { get; set; }
        public virtual TipoLocal TipoLocal { get; set; }
        public virtual TipoLocal TipoLocal1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
