//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class local
    {
        public local()
        {
            this.eventoes = new HashSet<evento>();
            this.listafavoritos = new HashSet<listafavorito>();
        }
    
        public int id { get; set; }
        public string user { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public int telefono { get; set; }
        public int idTipoLocal { get; set; }
        public int idDireccion { get; set; }
    
        public virtual direccion direccion { get; set; }
        public virtual ICollection<evento> eventoes { get; set; }
        public virtual ICollection<listafavorito> listafavoritos { get; set; }
        public virtual tipolocal tipolocal { get; set; }
    }
}
