//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionEventos.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eventosEntities : DbContext
    {
        public eventosEntities()
            : base("name=eventosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Direccion> Direccion { get; set; }
        public DbSet<Estilo> Estilo { get; set; }
        public DbSet<Evento> Evento { get; set; }
        public DbSet<Flyer> Flyer { get; set; }
        public DbSet<Local> Local { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<TipoEvento> TipoEvento { get; set; }
        public DbSet<TipoLocal> TipoLocal { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<ListaEvento> ListaEvento { get; set; }
        public DbSet<ListaFavoritos> ListaFavoritos { get; set; }
    }
}
